"""Test migration

Revision ID: decfe3770402
Revises: 4e345392e82f
Create Date: 2024-12-03 17:57:19.146702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decfe3770402'
down_revision = '4e345392e82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debit', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('credit', sa.String(length=100), nullable=True))
        batch_op.drop_column('is_credit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_credit', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('credit')
        batch_op.drop_column('debit')

    # ### end Alembic commands ###
